dist: trusty
language: ruby

cache: bundler

rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1

gemfile:
  - gemfiles/activesupport-4.0
  - gemfiles/activesupport-4.1
  - gemfiles/activesupport-4.2
  - gemfiles/activesupport-5.0
  - gemfiles/activesupport-5.1

matrix:
  exclude:
    - {rvm: '2.1.10', gemfile: 'gemfiles/activesupport-5.0'}
    - {rvm: '2.1.10', gemfile: 'gemfiles/activesupport-5.1'}
    - {rvm: '2.4.1', gemfile: 'gemfiles/activesupport-4.0'}
    - {rvm: '2.4.1', gemfile: 'gemfiles/activesupport-4.1'}

before_install:
  - gem install bundler --no-doc

script: bundle exec rspec
